### PR TITLE
fix: compatible for windows path with Chinese characters

### LINKED ISSUE #82: windows: 中文路径打开失败
项目路径带中文时打开失败

### PR DESCRIPTION
**Pull request by zh-lx**
close #82 

On windows, when the path has Chinese characters, the output of processes from powershell will has messy code.

So before exec `powershell -NoProfile -Command "Get-CimInstance -Query \\"select executablepath from win32_process where executablepath is not null\\" | % { $_.ExecutablePath }"`. We need exec `chcp 65001` to make the output compatible for Chinese characters firstly.

### CODE REVIEW

File: packages/launch-editor/guess.js [hunk 1]
```diff
@@ -56,6 +56,8 @@ module.exports = function guessEditor (specifiedEditor) {
         }
       }
     } else if (process.platform === 'win32') {
+      // compatible for path with Chinese characters
+      childProcess.execSync('chcp 65001');
       const output = childProcess
         .execSync(
           'powershell -NoProfile -Command "Get-CimInstance -Query \\"select executablepath from win32_process where executablepath is not null\\" | % { $_.ExecutablePath }"',
```
Comment (sapphi-red) [inline packages/launch-editor/guess.js:63]:
```suggestion
      const output = childProcess
        .execSync(
          'powershell -NoProfile -Command "' +
            '[Console]::OutputEncoding=[Text.Encoding]::UTF8;' +
            'Get-CimInstance -Query \\"select executablepath from win32_process where executablepath is not null\\" | % { $_.ExecutablePath }' +
            '"',
```
I think this is better. This way

- it does not call a separate command. Calling each command has an overhead.
- it does not call `chcp` (which probably effects for all command executed later on).

**Review by haoqunjiang — APPROVED** [review]
Works like a charm. Thank you both!!
